import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import companiesRouter from "./companies";
import employeesRouter from "./employees";
import attendanceRouter from "./attendance";
import devicesRouter from "./devices";
import payrollRouter from "./payroll";
import reportsRouter from "./reports";
import telegramRouter from "./telegram";
import departmentsRouter from "./departments";
import leaveRequestsRouter from "./leave_requests";
import settingsRouter from "./settings";
import joinRouter from "./join";
import advancesRouter from "./advances";
import staffRouter from "./staff";
import platformAdminRouter from "./platform-admin";
import exportRouter from "./export";
import analyticsRouter from "./analytics";
import broadcastingRouter from "./broadcasting";
import shiftsRouter from "./shifts";
import meRouter from "./me";
import auditLogRouter from "./audit-log";
import integrationsRouter from "./integrations";
import cvMonitorRouter from "./cv-monitor";
import govExportRouter from "./gov-export";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/companies", companiesRouter);
router.use("/employees", employeesRouter);
router.use("/attendance", attendanceRouter);
router.use("/devices", devicesRouter);
router.use("/payroll", payrollRouter);
router.use("/reports", reportsRouter);
router.use("/telegram", telegramRouter);
router.use("/departments", departmentsRouter);
router.use("/leave-requests", leaveRequestsRouter);
router.use("/settings", settingsRouter);
router.use("/join", joinRouter);
router.use("/advances", advancesRouter);
router.use("/staff", staffRouter);
router.use("/platform-admin", platformAdminRouter);
router.use("/export", exportRouter);
router.use("/analytics", analyticsRouter);
router.use("/broadcasting", broadcastingRouter);
router.use("/shifts", shiftsRouter);
router.use("/me", meRouter);
router.use("/audit-log", auditLogRouter);
router.use("/integrations", integrationsRouter);
router.use("/cv-monitor", cvMonitorRouter);
router.use("/gov-export", govExportRouter);

export default router;
